1️⃣ Replace Values in a Column

Problem:
You have a dataset of students’ majors. Some entries are incorrect. Replace the wrong values with the correct ones in one .replace() call.

Task:
Replace 'Busniess' → 'Business' and 'Phsycology' → 'Psychology'.

In [2]:
import pandas as pd

data = {
    'Student': ['Ava', 'Ben', 'Chloe', 'Dylan', 'Ella', 'Finn'],
    'Major': ['Busniess', 'Psychology', 'Busniess', 'Biology', 'Phsycology', 'Math']
}

df = pd.DataFrame(data)
df

  Student       Major
0     Ava    Busniess
1     Ben  Psychology
2   Chloe    Busniess
3   Dylan     Biology
4    Ella  Phsycology
5    Finn        Math

In [2]:
df['Major'] = df['Major'].replace({'Busniess': 'Business', 'Phsycology': 'Psychology'})
df

  Student       Major
0     Ava    Business
1     Ben  Psychology
2   Chloe    Business
3   Dylan     Biology
4    Ella  Psychology
5    Finn        Math

2️⃣ Subset → Group → Aggregate → Filter in One Line

Problem:
Using the dataset below, find the average score by subject for students who scored above 60, and keep only subjects where the average score ≥ 80.

In [5]:
data = {
    'Student': ['Ava', 'Ben', 'Chloe', 'Dylan', 'Ella', 'Finn', 'Grace', 'Hank'],
    'Subject': ['Math', 'Math', 'Science', 'Science', 'Math', 'Science', 'Math', 'Science'],
    'Score': [92, 58, 84, 77, 88, 91, 79, 83]
}
df = pd.DataFrame(data)

In [6]:
df[df['Score'] > 60].groupby('Subject')['Score'].mean().\
    reset_index().query('Score >= 80')

   Subject      Score
0     Math  86.333333
1  Science  83.750000

3️⃣ Recode Numeric Variable into Categories

Problem:
Given ages of employees, create a new column 'Age_Group' with:

"Young" for < 30

"Mid" for 30–50

"Senior" for > 50

In [3]:
data = {'Name': ['Ava', 'Ben', 'Chloe', 'Dylan', 'Ella'],
        'Age': [25, 32, 47, 53, 29]}
df = pd.DataFrame(data)

In [4]:
#solution
df['Age_Group'] = pd.cut(df['Age'],
                         bins=[0, 30, 50, 100],
                         labels=['Young', 'Mid', 'Senior'],
                         right=False)
df

    Name  Age Age_Group
0    Ava   25     Young
1    Ben   32       Mid
2  Chloe   47       Mid
3  Dylan   53    Senior
4   Ella   29     Young

4️⃣ Group, Aggregate, and Sort

Problem:
You have the following sales data. Group by 'Product', calculate total sales and average price, and sort by total sales (descending) — in one chained statement.

In [5]:
data = {
    'Product': ['Pen', 'Pen', 'Notebook', 'Notebook', 'Pencil', 'Pencil'],
    'Units': [10, 15, 20, 25, 30, 10],
    'Price': [1.5, 1.4, 3.0, 3.2, 0.8, 1.0]
}
df = pd.DataFrame(data)

In [6]:
#solution
df.groupby('Product', as_index=False).agg(
    total_sales=('Units', 'sum'),
    avg_price=('Price', 'mean')
).sort_values('total_sales', ascending=False)

    Product  total_sales  avg_price
0  Notebook           45       3.10
2    Pencil           40       0.90
1       Pen           25       1.45

5️⃣ Rename One Column

Problem:
Rename column 'Units' to 'Quantity' while keeping all other column names unchanged.

In [7]:
df = pd.DataFrame({
    'Product': ['Pen', 'Pencil', 'Notebook'],
    'Units': [25, 40, 30],
    'Price': [1.5, 0.8, 3.0]
})

In [8]:
#solution
df = df.rename(columns={'Units': 'Quantity'})
df

    Product  Quantity  Price
0       Pen        25    1.5
1    Pencil        40    0.8
2  Notebook        30    3.0

6️⃣ Merge Two DataFrames

Problem:
Merge two DataFrames on 'Product'. Add the 'Category' column from the second DataFrame into the first.

In [9]:
sales = pd.DataFrame({
    'Product': ['Pen', 'Pencil', 'Notebook'],
    'Price': [1.5, 0.8, 3.0]
})

categories = pd.DataFrame({
    'Product': ['Pen', 'Pencil', 'Notebook'],
    'Category': ['Stationery', 'Stationery', 'Office Supplies']
})

In [10]:
#solution
merged_df = sales.merge(categories, on='Product', how='left')
merged_df

    Product  Price         Category
0       Pen    1.5       Stationery
1    Pencil    0.8       Stationery
2  Notebook    3.0  Office Supplies