# <span style="color:red"> QTM 151 - Practice Quiz </span>

<font size = "5">

Import pandas

In [1]:
import pandas as pd


<font size = "5">

(1) Replace the values of a column

<font size = "3">

- Consider the DataFrame ``df_movies`` created below.
- In the "country" column, change the values "American" and "Korean" to "USA" and "ROK" respectively
- Do this by using the ``.replace`` method.

In [2]:
# create example DataFrame - don't change this
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
country = ["American", "American", "France", "Korean", "Thailand", "Korean", "France",
    "France", "Japan", "Italy", "American"]
runtime = [106, 119, 108, 120, 97, 115, 96, 91, 88, 98, 120]
year = [2023, 1941, 2017, 2017, 2004, 2003, 1967, 1964, 1977, 1977, 1986]
movie_dict = {"title" : titles, "country" : country, "runtime" : runtime, "year" : year}
df_movies = pd.DataFrame(movie_dict)
print(df_movies)


# your answer here

df_movies["country"] = df_movies["country"].replace(["American", "Korean"], 
                            ["USA", "ROK"])
print()
print(df_movies)

                         title   country  runtime  year
0                   Past Lives  American      106  2023
1                 Citizen Kane  American      119  1941
2                      Revenge    France      108  2017
3                         Okja    Korean      120  2017
4                      Shutter  Thailand       97  2004
5        A Tale of Two Sisters    Korean      115  2003
6                  La Chinoise    France       96  1967
7   The Umbrellas of Cherbourg    France       91  1964
8                        House     Japan       88  1977
9                     Suspiria     Italy       98  1977
10                 Blue Velvet  American      120  1986

                         title   country  runtime  year
0                   Past Lives       USA      106  2023
1                 Citizen Kane       USA      119  1941
2                      Revenge    France      108  2017
3                         Okja       ROK      120  2017
4                      Shutter  Thailand       97  2004
5        A Tale of Two Sisters       ROK      115  2003
6                  La Chinoise    France       96  1967
7   The Umbrellas of Cherbourg    France       91  1964
8                        House     Japan       88  1977
9                     Suspiria     Italy       98  1977
10                 Blue Velvet       USA      120  1986

<font size = "5">

(2) Recode a numeric column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories:

$\qquad$ ``` ["1941-1967","1968-1999","2000-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [3]:
# your code here

df_movies["year_brackets"] = pd.cut(x = df_movies["year"], 
                bins=[1940, 1967, 1999, float("inf")], 
                labels = ["1941-1967", "1968-1999", "2000-onwards"])

print(df_movies)

                         title   country  runtime  year year_brackets
0                   Past Lives       USA      106  2023  2000-onwards
1                 Citizen Kane       USA      119  1941     1941-1967
2                      Revenge    France      108  2017  2000-onwards
3                         Okja       ROK      120  2017  2000-onwards
4                      Shutter  Thailand       97  2004  2000-onwards
5        A Tale of Two Sisters       ROK      115  2003  2000-onwards
6                  La Chinoise    France       96  1967     1941-1967
7   The Umbrellas of Cherbourg    France       91  1964     1941-1967
8                        House     Japan       88  1977     1968-1999
9                     Suspiria     Italy       98  1977     1968-1999
10                 Blue Velvet       USA      120  1986     1968-1999

<font size = "5">

(3) Rename column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Rename the column "runtime" to "runtime(minutes)"

In [4]:
# Write your answer here:

df_movies.rename(columns={"runtime" : "runtime(minutes)"}, inplace=True)

print(df_movies)

                         title   country  runtime(minutes)  year year_brackets
0                   Past Lives       USA               106  2023  2000-onwards
1                 Citizen Kane       USA               119  1941     1941-1967
2                      Revenge    France               108  2017  2000-onwards
3                         Okja       ROK               120  2017  2000-onwards
4                      Shutter  Thailand                97  2004  2000-onwards
5        A Tale of Two Sisters       ROK               115  2003  2000-onwards
6                  La Chinoise    France                96  1967     1941-1967
7   The Umbrellas of Cherbourg    France                91  1964     1941-1967
8                        House     Japan                88  1977     1968-1999
9                     Suspiria     Italy                98  1977     1968-1999
10                 Blue Velvet       USA               120  1986     1968-1999

<font size = "5">

(4) Merge dataset

<font size = "3">

- Consider the DataFrames ``df_movies`` (created above) and ``df_scores`` (created below)
- Create a new dataset using  ```pd.merge()``` using <br>
"df_movies" as the primary dataset, and <br>
"df_scores" as the secondary dataset, merging on <br>
the column "title"
- You should **ONLY** merge the "imdb_score" column <br>
from the secondary dataset (not the "director" column)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging

In [5]:
# create example DataFrame - don't change this
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
scores = [7.8, 8.2, 6.4, 7.3, 7.0, 7.1, 6.9, 7.8, 7.2, 7.3, 7.7]
directors = ["Celine Song", "Orson Welles", "Coralie Fargeat", "Bong Joon Ho", 
    "Banjong Pisanthanakun", "Kim Jee-woon", "Jean-Luc Godard", "Jacques Demy", 
    "Nobuhiko Obayashi", "Dario Argento", "David Lynch"]

movie_dict2 = {"title" : titles, "imdb_score" : scores, "director" : directors}
df_scores = pd.DataFrame(movie_dict2)



# Write your answer here:

df_new = pd.merge(left = df_movies, right = df_scores[["title", "imdb_score"]], 
        on = "title", how = "left")
print(df_new)

                         title   country  runtime(minutes)  year  \
0                   Past Lives       USA               106  2023
1                 Citizen Kane       USA               119  1941
2                      Revenge    France               108  2017
3                         Okja       ROK               120  2017
4                      Shutter  Thailand                97  2004
5        A Tale of Two Sisters       ROK               115  2003
6                  La Chinoise    France                96  1967
7   The Umbrellas of Cherbourg    France                91  1964
8                        House     Japan                88  1977
9                     Suspiria     Italy                98  1977
10                 Blue Velvet       USA               120  1986

   year_brackets  imdb_score
0   2000-onwards         7.8
1      1941-1967         8.2
2   2000-onwards         6.4
3   2000-onwards         7.3
4   2000-onwards         7.0
5   2000-onwards         7.1
6      1941-1967         6.9
7      1941-1967         7.8
8      1968-1999         7.2
9      1968-1999         7.3
10     1968-1999         7.7

<font size = "5">

(5) Aggregate and sort

<font size = "3">

- Using the merged dataset you created above, do the following in a single line by chaining:
    - Group the dataset by "country"
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score
    - Score by average IMBD score in **descending order**

Print the resulting DataFrame

In [6]:
# Write your answer here:

(df_new.groupby("country").agg(avg_run = ('runtime(minutes)', 'mean'),
                    max_run = ('runtime(minutes)', 'max'),
                    avg_imdb = ('imdb_score', 'mean'),
                    min_imdb = ('imdb_score', 'min')).
                    sort_values(by = "avg_imdb", ascending = False))

             avg_run  max_run  avg_imdb  min_imdb
country
USA       115.000000      120  7.900000       7.7
Italy      98.000000       98  7.300000       7.3
Japan      88.000000       88  7.200000       7.2
ROK       117.500000      120  7.200000       7.1
France     98.333333      108  7.033333       6.4
Thailand   97.000000       97  7.000000       7.0

<font size = "5">

(6) Query and Aggregate

<font size = "3">

Using the merged dataset you created above, do the following in a single line by chaining:

- Subset the observations for 'country == France' using ```.query()```
- Sort the values by year (oldest first)
- Extract the two oldest movies

Print the resulting DataFrame to the screen

In [7]:
# Write your answer here:

df_new.query("country == 'France'").sort_values(by = "year").iloc[:2,:]

,title,country,runtime(minutes),year,year_brackets,imdb_score
7,The Umbrellas of Cherbourg,France,91,1964,1941-1967,7.8
6,La Chinoise,France,96,1967,1941-1967,6.9